### ISSUE TITLE
Installer doesn't start service on boot on systems where rc.local does not exist

### ISSUE THREAD

**Issue by WilliamsJack** [SFXRescue/SIGHTSRobot#24]
It appears the file rc.local does not exist in a fresh installation of Ubuntu 18.04.
`install.sh` assumes the file exists:
```bash
echo -e "\nAdding supervisord to /etc/rc.local..."
    if grep -Fxq "supervisord &" /etc/rc.local
    then
        echo -e "Already done..."
    else
        sed -i -e '$i \supervisord &\n' /etc/rc.local
    fi
```

Manually creating `rc.local` and adding the lines:
```bash
#!/bin/sh -e
supervisord
exit 0
```
and running `sudo chmod +x /etc/rc.local` has the desired effect of running SIGHTS on boot.

At this stage we can either update the install script to check for the missing file and create it if necessary, or find some alternative for starting the service on boot that will work with more operating systems.

**Comment by Conr86** [comment]
Allegedly, according to [this post](https://bencane.com/2011/12/30/when-its-ok-and-not-ok-to-use-rc-local/), Debian does not support the use of rc.local. I believe that Rasbian does, or at least it used to.

I think it's worth doing it properly. The official recommended way would be this: https://github.com/Supervisor/initscripts

Although the init scripts differ depending on distribution which makes it a bit trickier.
