### ISSUE TITLE
Current proxy directives causing screenshot download issues.

### ISSUE THREAD

**Issue by WilliamsJack** [SFXRescue/SIGHTSRobot#30]
**Describe the bug**
Screenshot downloads fail. Browser says "Failed - Server problem" and I get a 502 proxy error when visiting `http://192.168.1.201/stream/1/current`. Apache error log is equally unhelpful, "_specific information not available_":
```
[Wed Nov 20 16:10:18.864577 2019] [proxy_http:error] [pid 2287:tid 140147651761920] (20014)Internal error (specific information not available): [client 192.168.1.211:62223] AH01102: error reading status line from remote server localhost:8081     
[Wed Nov 20 16:10:18.864650 2019] [proxy:error] [pid 2287:tid 140147651761920] [client 192.168.1.211:62223] AH00898: Error reading from remote server returned by /stream/1/current
```

This is an odd issue considering screenshot downloads were working just a few days ago. Perhaps a recent Ubuntu or Apache patch has changed something?

Current proxy directives in `SIGHTSInterface.conf`:
```
    ProxyPass "/stream" "http://localhost:8081/"
    ProxyPassReverse "/stream" "http://localhost:8081/"
```

![image](https://user-images.githubusercontent.com/30068301/69211166-48feda80-0bb1-11ea-88aa-825bb52f5cfc.png)

The two downloads on the right (pictured above) were done with the trailing forward slash on the remote url argument of the proxy directives.
The slash was removed, Apache restarted, and the downloads were attempted again, resulting in the two successes shown on the left.

Proposed new proxy directives (trailing forward slash removed):
```
    ProxyPass "/stream" "http://localhost:8081"
    ProxyPassReverse "/stream" "http://localhost:8081"
```

I'm creating this issue to see if other people can reproduce this behaviour.
Regardless of whether you are able to reproduce, try removing the trailing forward slash in the proxy directives in the `SIGHTSInterface.conf` site. Please report the results for both tests.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Click the screenshot button on a running stream

**Expected behaviour**
The screenshot should download.

**Host/Robot Information:**
 - OS: Ubuntu
 - OS Version: 18.04.3 LTS

**Controller (where you access the interface from. Remove this section if you weren't using the interface):**
 - OS: Windows 10
 - OS Version Build 18362
 - Browser: Chrome
 - Browser version: 78.0.3904.97

**Comment by Conr86** [comment]
Awesome, so I was able to reproduce the problem exactly, and removing the trailing slash did indeed fix it, so it looks like that's all we have to do 👍

> Perhaps a recent Ubuntu or Apache patch has changed something?

That's certainly possible. Although keep in mind I'm running Debian, which isn't known for getting updates quickly. I don't recall us making any other changes that could cause this though. 

**Host/Robot Information:**
- OS: Debian
- OS Version: 10 Buster

**Controller (where you access the interface from. Remove this section if you weren't using the interface):**
- OS: Windows 10
- OS Version Build 18992
- Browser: Edge Dev (Chromium)
- Browser version: 80.0.334.3

**Comment by WilliamsJack** [comment]
Fortunately, it's an easy fix, but I still can't think of any other possible cause.

Fix for new installations: None required

Fix for existing installations: Run `install.sh` option 8 (update) and then option 4 to copy the new apache config.
